version: '3'

services:
    routeasy:
        build: .
        container_name: challenge
        environment:
            - PORT=3000
            - DELIVERY_DB_URI=mongo:27017
        ports:
            - "3000:3000"
        volumes:
            - './src:/home/app/src'
            - './test:/home/app/test'
            - './package.json:/home/app/package.json'
        depends_on:
            - mongo

    mongo:
        image: mongo:3.4
        volumes:
            - '/data/db:/data/db'